#Global settings
# include: [.htaccess]
encoding: utf-8

#build command setting
# lsi: true

# Site settings
title: leafsummer's blog
email: wing.sun1987@gmail.com
description: "this is the leafsummer's github pages blog, created by jekyll"
baseurl: /myblog
url: "http://leafsummer.github.io/myblog/"
twitter_username: leafsummer
github_username:  leafsummer
# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty